enum PRODUCT_CONSTANTS {

    FETCH_PRODUCT_CATALOG_REQUEST = "FETCH_PRODUCT_CATALOG_REQUEST",
    FETCH_PRODUCT_CATALOG_SUCCESS = "FETCH_PRODUCT_CATALOG_SUCCESS",
    FETCH_PRODUCT_CATALOG_FAIL = "FETCH_PRODUCT_CATALOG_FAIL"
    
}

export default PRODUCT_CONSTANTS;