enum PRODUCT_CONSTANTS {

    FETCH_PRODUCT_CATALOG_REQUEST = "FETCH_PRODUCT_CATALOG_REQUEST",
    FETCH_PRODUCT_CATALOG_SUCCESS = "FETCH_PRODUCT_CATALOG_SUCCESS",
    FETCH_PRODUCT_CATALOG_FAIL = "FETCH_PRODUCT_CATALOG_FAIL",

    SAVE_CURRENT_PRODUCT = "SAVE_CURRENT_PRODUCT"
    
}

export default PRODUCT_CONSTANTS;