enum CART_CONSTANTS {

    ADD_TO_CART = "ADD_TO_CART",
    CART_UPDATE = "CART_UPDATE",
    DELETE_FROM_CART = "DELETE_FROM_CART",
    CLEAR_ALERTS = "CLEAR_ALERTS",
    EXIST_PRODUCT_ALERT= "EXIST_PRODUCT_ALERT"
}

export default CART_CONSTANTS;